[tool.poetry]
name = "poetry-shit"
version = "0.1.0"
description = ""
authors = ["meh"]
readme = "README.md"
packages = [{include = "poetry_shit"}]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
